server_list = [
    {'name': 'StuntRocket',
     'url': 'https://stuntrocket.co',
     'timeout': 300,
     'max_fails': 1,
     'assert_string': 'Hand Crafted Web'},
    {'name': 'Instoria',
     'url': 'https://instoria.co.uk',
     'timeout': 300,
     'max_fails': 1,
     'assert_string': 'Instore Retail App'},
    {'name': 'Geyser',
     'url': 'https://www.geyser.co.uk',
     'timeout': 300,
     'max_fails': 1,
     'assert_string': 'Call us on'},
    {'name': 'Clever Fish',
     'url': 'https://thecleverfish.co.uk',
     'timeout': 300,
     'max_fails': 1,
     'assert_string': 'The Clever Fish Recruitment'},
    {'name': 'CAP',
     'url': 'https://fuelpovertyresource.org.uk',
     'timeout': 300,
     'max_fails': 1,
     'assert_string': 'Fuel Poverty Resources'},
    {'name': 'Cryogenic API',
     'url': 'https://cryo.mbhub.duckdns.org',
     'timeout': 300,
     'max_fails': 1,
     'assert_string': 'Cryogenic'},
    {'name': 'Pingspect API',
     'url': 'https://api.pingspect.com',
     'timeout': 300,
     'max_fails': 1,
     'assert_string': 'Pingspect'}
]